// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvg9Ez0y9uz1URiBR_OXK5rCbVmLI0YKs',
    appId: '1:621096230849:web:d0aed38fc421fedf685940',
    messagingSenderId: '621096230849',
    projectId: 'praktikum-laras',
    authDomain: 'praktikum-laras.firebaseapp.com',
    storageBucket: 'praktikum-laras.appspot.com',
    measurementId: 'G-TSCYXVQYQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4wFnEu-oMtWuyparUeiAjNgf6hhCJppI',
    appId: '1:621096230849:android:fbcf16b37fea8173685940',
    messagingSenderId: '621096230849',
    projectId: 'praktikum-laras',
    storageBucket: 'praktikum-laras.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8R1mhjdd8xSS3Qwc9I7WXaplSiGoRKgw',
    appId: '1:621096230849:ios:da013c7f03ba3d32685940',
    messagingSenderId: '621096230849',
    projectId: 'praktikum-laras',
    storageBucket: 'praktikum-laras.appspot.com',
    iosBundleId: 'com.example.pertemuan9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8R1mhjdd8xSS3Qwc9I7WXaplSiGoRKgw',
    appId: '1:621096230849:ios:da013c7f03ba3d32685940',
    messagingSenderId: '621096230849',
    projectId: 'praktikum-laras',
    storageBucket: 'praktikum-laras.appspot.com',
    iosBundleId: 'com.example.pertemuan9',
  );

}