// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZx1idBzEFYXMrqEQGZKtRWyNvh8b67Fw',
    appId: '1:421394465957:web:67d268af26eb5e7d89394c',
    messagingSenderId: '421394465957',
    projectId: 'praktikum6-ecbe3',
    authDomain: 'praktikum6-ecbe3.firebaseapp.com',
    storageBucket: 'praktikum6-ecbe3.appspot.com',
    measurementId: 'G-CRPH31MXWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMCqATVDflYHCRTSc8t4X3r6RJN-4_1-k',
    appId: '1:421394465957:android:79e7e7a937d7c7c589394c',
    messagingSenderId: '421394465957',
    projectId: 'praktikum6-ecbe3',
    storageBucket: 'praktikum6-ecbe3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuCQg3fdQz-26u_-baYdx54JkaBVOkaD4',
    appId: '1:421394465957:ios:07459f21e4628ca689394c',
    messagingSenderId: '421394465957',
    projectId: 'praktikum6-ecbe3',
    storageBucket: 'praktikum6-ecbe3.appspot.com',
    iosBundleId: 'com.example.pertemuan9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuCQg3fdQz-26u_-baYdx54JkaBVOkaD4',
    appId: '1:421394465957:ios:07459f21e4628ca689394c',
    messagingSenderId: '421394465957',
    projectId: 'praktikum6-ecbe3',
    storageBucket: 'praktikum6-ecbe3.appspot.com',
    iosBundleId: 'com.example.pertemuan9',
  );
}
